version: "syntax-highlight-theme.{build}"

os: Visual Studio 2017

platform:
  - x64

branches:
  only:
    - master

skip_non_tags: true

init:
  - npm --version

install:
  - npm update
  - npm install -g vsce

build_script:
  - vsce package

after_build:
  - vsce publish -p ihrya2gw77tys3mo7pjjucwovfvi35wn5xppar3yvy4i3e6p67va

  # - set LatestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
  # - mv ./*.vsix %LatestTag%.vsix
  # - appveyor PushArtifact %LatestTag%.vsix


#deploy:
 # - provider: GitHub
  #  description: "auto build release"
   # auth_token:
    #  secure: b7z/bl9MpzzCY+CYah15JF9aJbut5gtIWcpiZOoZpVc41W7NmKOOeB40RO7HiiK/
    #draft: false
    #tag: Release%LatestTag%
    #on:
    #  APPVEYOR_REPO_TAG: false
