import path from "node:path";
import url from "node:url";
import { getFullPath } from "./utils.js";

const __filename = url.fileURLToPath(import.meta.url);
const vscodePath = path.normalize("vscode/extensions");

export const workspaceRoot = path.resolve(path.dirname(__filename), "..");
export const dataRoot = getFullPath(workspaceRoot, "data");

export const tmLanguageDir = getFullPath(dataRoot, "tmLanguage");
export const scopeDir = getFullPath(dataRoot, "scope");
export const scopeCSVDir = getFullPath(dataRoot, "csv");
export const themesDir = getFullPath(dataRoot, "themes");

export const vscodeTmLanguageDir = getFullPath(tmLanguageDir, vscodePath);
export const vscodeScopeDir = getFullPath(scopeDir, vscodePath);
export const vscodeScopeCSVDir = getFullPath(scopeCSVDir, vscodePath);

export const defaultScopeFile = getFullPath(scopeDir, "default.scope.txt");
export const defaultScopeCSVFile = getFullPath(scopeCSVDir, "default.scope.csv");

export const defaultScopes = new Set([
    "comment.block",
    "comment.block.documentation",
    "comment.line",
    "comment.line.character",
    "comment.line.double-dash",
    "comment.line.double-slash",
    "comment.line.number-sign",
    "comment.line.percentage",
    "constant.character.escape",
    "constant.language",
    "constant.numeric",
    "constant.numeric.complex",
    "constant.numeric.complex.imaginary",
    "constant.numeric.complex.real",
    "constant.numeric.float",
    "constant.numeric.float.binary",
    "constant.numeric.float.decimal",
    "constant.numeric.float.hexadecimal",
    "constant.numeric.float.octal",
    "constant.numeric.float.other",
    "constant.numeric.integer",
    "constant.numeric.integer.binary",
    "constant.numeric.integer.decimal",
    "constant.numeric.integer.hexadecimal",
    "constant.numeric.integer.octal",
    "constant.numeric.integer.other",
    "constant.other",
    "constant.other.placeholder",
    "constant.regexp",
    "entity.name.class",
    "entity.name.class.forward-decl",
    "entity.name.constant",
    "entity.name.decorator",
    "entity.name.enum",
    "entity.name.function",
    "entity.name.function.constructor",
    "entity.name.function.destructor",
    "entity.name.function.member",
    "entity.name.function.preprocessor",
    "entity.name.impl",
    "entity.name.interface",
    "entity.name.label",
    "entity.name.namespace",
    "entity.name.section",
    "entity.name.struct",
    "entity.name.tag",
    "entity.name.trait",
    "entity.name.type",
    "entity.name.type.class",
    "entity.name.type.enum",
    "entity.name.type.interface",
    "entity.name.type.parameter",
    "entity.name.type.struct",
    "entity.name.union",
    "entity.name.variable",
    "entity.other.attribute-name",
    "entity.other.inherited-class",
    "invalid.deprecated",
    "invalid.illegal",
    "keyword.control",
    "keyword.control.conditional",
    "keyword.control.import",
    "keyword.declaration.class",
    "keyword.declaration.enum",
    "keyword.declaration.function",
    "keyword.declaration.impl",
    "keyword.declaration.interface",
    "keyword.declaration.struct",
    "keyword.declaration.trait",
    "keyword.declaration.type",
    "keyword.declaration.union",
    "keyword.operator",
    "keyword.operator.arithmetic",
    "keyword.operator.assignment",
    "keyword.operator.bitwise",
    "keyword.operator.logical",
    "keyword.operator.word",
    "keyword.other",
    "markup.bold",
    "markup.deleted",
    "markup.heading",
    "markup.inserted",
    "markup.italic",
    "markup.list.numbered",
    "markup.list.unnumbered",
    "markup.other",
    "markup.quote",
    "markup.raw",
    "markup.raw.block",
    "markup.raw.inline",
    "markup.underline",
    "markup.underline.link",
    "meta.annotation",
    "meta.annotation.identifier",
    "meta.annotation.parameters",
    "meta.block",
    "meta.braces",
    "meta.brackets",
    "meta.class",
    "meta.embedded.assembly",
    "meta.enum",
    "meta.function",
    "meta.function-call",
    "meta.function.parameters",
    "meta.function.return-type",
    "meta.generic",
    "meta.group",
    "meta.impl",
    "meta.interface",
    "meta.interpolation",
    "meta.namespace",
    "meta.paragraph",
    "meta.parens",
    "meta.path",
    "meta.preprocessor",
    "meta.string",
    "meta.struct",
    "meta.tag",
    "meta.toc-list",
    "meta.trait",
    "meta.type",
    "meta.union",
    "punctuation.accessor",
    "punctuation.definition.annotation",
    "punctuation.definition.comment",
    "punctuation.definition.generic.begin",
    "punctuation.definition.generic.end",
    "punctuation.definition.keyword",
    "punctuation.definition.string.begin",
    "punctuation.definition.string.end",
    "punctuation.definition.variable",
    "punctuation.section.block.begin",
    "punctuation.section.block.end",
    "punctuation.section.braces.begin",
    "punctuation.section.braces.end",
    "punctuation.section.brackets.begin",
    "punctuation.section.brackets.end",
    "punctuation.section.group.begin",
    "punctuation.section.group.end",
    "punctuation.section.interpolation.begin",
    "punctuation.section.interpolation.end",
    "punctuation.section.parens.begin",
    "punctuation.section.parens.end",
    "punctuation.separator",
    "punctuation.separator.continuation",
    "punctuation.terminator",
    "storage.modifier",
    "storage.type",
    "storage.type ",
    "storage.type.class ",
    "storage.type.enum ",
    "storage.type.function ",
    "storage.type.impl ",
    "storage.type.interface ",
    "storage.type.struct ",
    "storage.type.trait ",
    "storage.type.union ",
    "string.interpolated",
    "string.other",
    "string.quoted.double",
    "string.quoted.other",
    "string.quoted.single",
    "string.quoted.triple",
    "string.regexp",
    "string.unquoted",
    "support.class",
    "support.constant",
    "support.constant.property",
    "support.function",
    "support.module",
    "support.other",
    "support.other.variable",
    "support.type",
    "support.variable",
    "support.variable.property",
    "text.html.basic",
    "text.html.markdown",
    "variable.annotation",
    "variable.language",
    "variable.other",
    "variable.other.constant",
    "variable.other.constant.property",
    "variable.other.enummember",
    "variable.other.event",
    "variable.other.member",
    "variable.other.property",
    "variable.other.readwrite",
    "variable.parameter",
]);
