name: Code quality - Biome lint

on:
  push:
  pull_request:

jobs:
  quality:
    name: Code quality - Biome lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci .
